# Generated by Django 4.1.3 on 2022-12-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='author',
        ),
    ]
